# Generated by Django 6.0.5 on 2026-05-26 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_review_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comment',
        ),
    ]
