# Generated by Django 6.0.5 on 2026-05-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_id_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=12),
            preserve_default=False,
        ),
    ]
